export const subjectList = [
"apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew", "kiwi", "lemon",
"mango", "nectarine", "orange", "papaya", "quince", "raspberry", "strawberry", "tangerine", "ugli",
"vanilla", "watermelon", "xigua", "yam", "zucchini", "apricot", "blackberry", "cantaloupe", "dragonfruit",
"eggplant", "feijoa", "guava", "huckleberry", "imbe", "jackfruit", "kumquat", "lime", "mulberry", "nutmeg",
"olive", "peach", "quandong", "rambutan", "salak", "tamarind", "ugni", "voavanga", "wolfberry", "ximenia",
"yuzu", "ziziphus", "acai", "bilberry", "clementine", "damson", "elderflower", "fingerlime", "grapefruit",
"honeyberry", "jabuticaba", "kiwano", "longan", "mandarin", "nashi", "opal", "persimmon", "quararibea",
"rowan", "soursop", "tangelo", "umbu", "vaccinium", "waxapple", "yellowpassionfruit", "zabergau",
"ackee", "boysenberry", "cloudberry", "dewberry", "entawak", "figs", "gooseberry", "hackberry", "ilama",
"jostaberry", "kabosu", "loganberry", "mangosteen", "naranjilla", "oroblanco", "pineapple", "quararibea",
"redcurrant", "santol", "tayberry", "ugni", "voavanga", "whitecurrant", "ximenia", "yangmei", "zinfandel",
"ambarella", "breadfruit", "cherimoya", "durian", "emblic", "feijoa", "grumichama", "hornedmelon", "indianfig",
"jambolan", "kaffirlime", "langsat", "mammeeapple", "noni", "osageorange", "pitanga", "quararibea",
"rambai", "sapodilla", "tamarillo", "ugni", "velvetapple", "whitecurrant", "ximenia", "yumberry", "zinfandel",
"abiu", "bignay", "cupuacu", "duku", "elephantapple", "farkleberry", "gac", "huito", "ilama", "jocote",
"karonda", "lucuma", "mamey", "naranjilla", "oroblanco", "pulasan", "quararibea", "rambai", "santol",
"tamarillo", "ugni", "velvetapple", "whitecurrant", "ximenia", "yangmei", "zinfandel", "acerola", "blackcurrant",
"camu", "dangleberry", "emblic", "feijoa", "grumichama", "hornedmelon", "indianfig", "jambolan", "kaffirlime",
"langsat", "mammeeapple", "noni", "osageorange", "pitanga", "quararibea", "rambai", "sapodilla", "tamarillo",
"ugni", "velvetapple", "whitecurrant", "ximenia", "yumberry", "zinfandel", "abiu", "bignay", "cupuacu", "duku",
"elephantapple", "farkleberry", "gac", "huito", "ilama", "jocote", "karonda", "lucuma", "mamey", "naranjilla",
"oroblanco", "pulasan", "quararibea", "rambai", "santol", "tamarillo", "ugni", "velvetapple", "whitecurrant",
"ximenia", "yangmei", "zinfandel", "acerola", "blackcurrant", "camu", "dangleberry", "emblic", "feijoa",
"grumichama", "hornedmelon", "indianfig", "jambolan", "kaffirlime", "langsat", "mammeeapple", "noni",
"osageorange", "pitanga", "quararibea", "rambai", "sapodilla", "tamarillo", "ugni", "velvetapple",
"whitecurrant", "ximenia", "yumberry", "zinfandel", "abiu", "bignay", "cupuacu", "duku", "elephantapple",
"farkleberry", "gac", "huito", "ilama", "jocote", "karonda", "lucuma", "mamey", "naranjilla", "oroblanco",
"pulasan", "quararibea", "rambai", "santol", "tamarillo", "ugni", "velvetapple", "whitecurrant", "ximenia",
"yangmei", "zinfandel", "acerola", "blackcurrant", "camu", "dangleberry", "emblic", "feijoa", "grumichama",
"hornedmelon", "indianfig", "jambolan", "kaffirlime", "langsat", "mammeeapple", "noni", "osageorange",
"pitanga", "quararibea", "rambai", "sapodilla", "tamarillo", "ugni", "velvetapple", "whitecurrant",
"ximenia", "yumberry", "zinfandel", "abiu", "bignay", "cupuacu", "duku", "elephantapple", "farkleberry",
"gac", "huito", "ilama", "jocote", "karonda", "lucuma", "mamey", "naranjilla", "oroblanco", "pulasan",
"quararibea", "rambai", "santol", "tamarillo", "ugni", "velvetapple", "whitecurrant", "ximenia", "yangmei",
"zinfandel", "acerola", "blackcurrant", "camu", "dangleberry", "emblic", "feijoa", "grumichama", "hornedmelon",
"indianfig", "jambolan", "kaffirlime", "langsat", "mammeeapple", "noni", "osageorange", "pitanga", "quararibea",
"rambai", "sapodilla", "tamarillo", "ugni", "velvetapple", "whitecurrant", "ximenia", "yumberry", "zinfandel",
"abiu", "bignay", "cupuacu", "duku", "elephantapple", "farkleberry", "gac", "huito", "ilama", "jocote",
"karonda", "lucuma", "mamey", "naranjilla", "oroblanco", "pulasan", "quararibea", "rambai", "santol",
"tamarillo", "ugni", "velvetapple", "whitecurrant", "ximenia", "yangmei", "zinfandel", "acerola",
"blackcurrant", "camu", "dangleberry", "emblic", "feijoa", "grumichama", "hornedmelon", "indianfig",
"jambolan", "kaffirlime", "langsat", "mammeeapple", "noni", "osageorange", "pitanga", "quararibea",
"rambai", "sapodilla", "tamarillo", "ugni", "velvetapple", "whitecurrant", "ximenia", "yumberry",
"zinfandel", "abiu", "bignay", "cupuacu", "duku", "elephantapple", "farkleberry", "gac", "huito",
"ilama", "jocote", "karonda", "lucuma", "mamey", "naranjilla", "oroblanco", "pulasan", "quararibea",
"rambai", "santol", "tamarillo", "ugni", "velvetapple", "whitecurrant", "ximenia", "yangmei", "zinfandel"
];
